// Generated by tools/build.mjs. Do not edit by hand.
export default [
  {
    "id": "01",
    "name": "Liquid Monolith",
    "blurb": "A standing slab of liquid chrome. Ripples chase your cursor across its face."
  },
  {
    "id": "02",
    "name": "Orbital Gyroscope",
    "blurb": "Rings of light spin on independent axes around an obsidian core. Your cursor tilts the whole rig."
  },
  {
    "id": "03",
    "name": "Particle Galaxy",
    "blurb": "A spiral galaxy of twenty thousand stars. Your cursor acts as a gravity well that gathers and swirls them."
  },
  {
    "id": "04",
    "name": "Glass Prism",
    "blurb": "White light enters a glass prism and fans out into a cold spectrum. Your cursor steers the beam."
  },
  {
    "id": "05",
    "name": "Wireframe Ridges",
    "blurb": "An endless night flight over glowing wireframe mountains beneath a full moon. Your cursor banks the camera."
  },
  {
    "id": "06",
    "name": "Silk Ribbons",
    "blurb": "Satin ribbons ripple and twist like fabric in the wind. Your cursor gathers them toward it."
  },
  {
    "id": "07",
    "name": "Pulse Grid",
    "blurb": "A floor of hexagonal pillars. Waves of light and motion ripple outward from wherever your cursor rests."
  },
  {
    "id": "08",
    "name": "Field Lines",
    "blurb": "A magnetic dipole traced in light, with particles streaming along its field loops. Your cursor swings the axis."
  },
  {
    "id": "09",
    "name": "Crystal Geode",
    "blurb": "A cluster of quartz grows from black rock, glowing from within. Your cursor moves the light inside it."
  },
  {
    "id": "10",
    "name": "Deep Jellyfish",
    "blurb": "A bioluminescent jellyfish pulses through the deep, trailing threads of light. It slowly swims toward your cursor."
  },
  {
    "id": "11",
    "name": "Tesseract",
    "blurb": "A hypercube rotating through the fourth dimension, projected into ours. Your cursor sets the speed and plane of its turn."
  },
  {
    "id": "22",
    "name": "Shattered Mirror",
    "blurb": "A mirror full of night sky that fractures and heals. Shards scatter from your cursor."
  },
  {
    "id": "23",
    "name": "Pendulum Wave",
    "blurb": "Eighteen glowing pendulums slipping in and out of phase. Move to swing the camera around them."
  },
  {
    "id": "24",
    "name": "Möbius Band",
    "blurb": "A lacquered Möbius strip where light runs its single endless surface. Your cursor turns it."
  },
  {
    "id": "25",
    "name": "Knot Current",
    "blurb": "Energy races through a smoked-glass knot. The further your cursor strays, the faster it flows."
  },
  {
    "id": "26",
    "name": "Night City",
    "blurb": "A rain-streaked skyline gliding past in the dark. Your cursor steers the fly-over."
  },
  {
    "id": "27",
    "name": "Lighthouse",
    "blurb": "A lighthouse sweeping its beam through sea fog. Point, and the light turns to find you."
  },
  {
    "id": "28",
    "name": "Signal Flag",
    "blurb": "A silk banner rippling in the night wind. Your cursor is a gust that billows the cloth."
  },
  {
    "id": "29",
    "name": "Radial Spectrum",
    "blurb": "A circular equaliser pumping to a silent beat on black glass. Bars rise to meet your cursor."
  },
  {
    "id": "30",
    "name": "Constellations",
    "blurb": "A deep field of stars. Wherever you point, nearby stars reach for each other and draw a constellation."
  },
  {
    "id": "31",
    "name": "Iridescent Bubbles",
    "blurb": "Blue-violet soap bubbles drifting in the dark. Sweep your cursor to blow them away."
  },
  {
    "id": "42",
    "name": "Fiber Bloom",
    "blurb": "Thousands of fibre-optic strands with glowing tips. Your cursor blows through them like wind."
  },
  {
    "id": "43",
    "name": "Mandelbulb",
    "blurb": "A living 3D fractal, morphing as it breathes. Move your cursor to orbit around it."
  },
  {
    "id": "44",
    "name": "Sky Lanterns",
    "blurb": "Paper lanterns rise over dark water. Your cursor releases new ones and nudges them aside."
  },
  {
    "id": "45",
    "name": "Kaleido Tunnel",
    "blurb": "A kaleidoscopic tunnel of mirrored crystal. Your cursor turns the prism and changes its symmetry."
  },
  {
    "id": "46",
    "name": "Shape Shifter",
    "blurb": "Fifteen thousand particles flowing between forms. Your cursor scatters the ones nearby."
  },
  {
    "id": "47",
    "name": "Light Maze",
    "blurb": "A beam of light solves a dark labyrinth, then a new one rises. Your cursor tilts the maze."
  },
  {
    "id": "48",
    "name": "Plasma Orb",
    "blurb": "A glass plasma ball crackling with lightning. One tendril reaches for your cursor."
  },
  {
    "id": "49",
    "name": "Twist Tower",
    "blurb": "A breathing tower of glossy stacked plates. Move your cursor sideways to wind or unwind the twist."
  },
  {
    "id": "50",
    "name": "Glow Reef",
    "blurb": "A bioluminescent reef of branching coral and drifting plankton. Coral near your cursor glows brighter."
  }
];
