// Generated by tools/build.mjs. Do not edit by hand.
export default [
  {
    "id": "01",
    "name": "Liquid Monolith",
    "blurb": "A standing slab of liquid chrome. Ripples chase your cursor across its face."
  },
  {
    "id": "02",
    "name": "Orbital Gyroscope",
    "blurb": "Rings of light spin on independent axes around an obsidian core. Your cursor tilts the whole rig."
  },
  {
    "id": "03",
    "name": "Particle Galaxy",
    "blurb": "A spiral galaxy of twenty thousand stars. Your cursor acts as a gravity well that gathers and swirls them."
  },
  {
    "id": "04",
    "name": "Glass Prism",
    "blurb": "White light enters a glass prism and fans out into a cold spectrum. Your cursor steers the beam."
  },
  {
    "id": "05",
    "name": "Wireframe Ridges",
    "blurb": "An endless night flight over glowing wireframe mountains beneath a full moon. Your cursor banks the camera."
  },
  {
    "id": "06",
    "name": "Silk Ribbons",
    "blurb": "Satin ribbons ripple and twist like fabric in the wind. Your cursor gathers them toward it."
  },
  {
    "id": "07",
    "name": "Pulse Grid",
    "blurb": "A floor of hexagonal pillars. Waves of light and motion ripple outward from wherever your cursor rests."
  },
  {
    "id": "08",
    "name": "Field Lines",
    "blurb": "A magnetic dipole traced in light, with particles streaming along its field loops. Your cursor swings the axis."
  },
  {
    "id": "09",
    "name": "Crystal Geode",
    "blurb": "A cluster of quartz grows from black rock, glowing from within. Your cursor moves the light inside it."
  },
  {
    "id": "10",
    "name": "Deep Jellyfish",
    "blurb": "A bioluminescent jellyfish pulses through the deep, trailing threads of light. It slowly swims toward your cursor."
  },
  {
    "id": "11",
    "name": "Tesseract",
    "blurb": "A hypercube rotating through the fourth dimension, projected into ours. Your cursor sets the speed and plane of its turn."
  }
];
