// Generated by tools/build.mjs. Do not edit by hand.
export default [
  {
    "id": "01",
    "name": "Liquid Monolith",
    "blurb": "A standing slab of liquid chrome. Ripples chase your cursor across its face."
  }
];
