/**
 * Regenerate designs/manifest.js from the dNN.js modules.
 *   node brandmotion-3d/tools/build.mjs
 */
process.removeAllListeners("warning");
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const dir = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../designs");
const files = fs.readdirSync(dir).filter((f) => /^d\d\d\.js$/.test(f)).sort();
const list = [];
for (const f of files) {
  const { default: d } = await import(pathToFileURL(path.join(dir, f)));
  list.push({ id: d.id, name: d.name, blurb: d.blurb, theme: d.theme || "midnight" });
}
fs.writeFileSync(
  path.join(dir, "manifest.js"),
  `// Generated by tools/build.mjs. Do not edit by hand.\nexport default ${JSON.stringify(list, null, 2)};\n`
);
console.log(`manifest: ${list.length} designs`);
